### ISSUE TITLE
It doesn't do anything?

### ISSUE THREAD

**Issue by LekoArts** [probot/stale-action#9]
Hi!

Thanks for creating the stale-action, highly appreciated! I'm currently testing out the action for Gatsby's monorepo in this test repository: https://github.com/LekoArts/stale-bot-test

I converted the outdated [workflow](https://github.com/probot/stale-action#creating-a-workflow-file) syntax to YAML: https://github.com/LekoArts/stale-bot-test/tree/master/.github/workflows

However, if you have a look at the Actions tab... It doesn't do anything 🤔 The test issues should already have been marked.

Am I'm doing something obviously wrong? Any help is appreciated. Thanks!

cc @JasonEtco @tcbyrd

**Comment by tcbyrd** [comment]
@LekoArts I'm not 💯sure why it's not working, but the Actions team has released an [official Stale action](http://github.com/actions/stale) that I'd recommend trying out. I'm going to archive this repo in favor of that one, since a lot has changed under the hood with Actions and it would more than likely require a completely re-write anyway.
